"""
continuity.py — auto-write `_continuity/STATE_<ts>.md` on shutdown.

Phase 2.2 added consumer-side continuity (the GUI reads STATE files
written by the Skill Agent). Ops-1 (2026-05-10) adds the producer
side: when the GUI process exits, it writes its own STATE so the
next session — Skill Agent or GUI — picks up where this one left
off.

What gets recorded:
- Last 20 audit_log entries (what changed in this session)
- Recent verifications (count by status)
- Recent learning_feedback (corrections this session)
- Recent llm_calls (Claude calls + cost)
- Active project info
- Latest snapshot

The file is gitignored if the user doesn't want them in version
control, but the default is to commit them — they're cheap and
useful as a project log.
"""

from __future__ import annotations

import os
import sys
from datetime import datetime, timezone
from pathlib import Path

from . import database as db


def write_session_state(*, root: Path, session_id: str | None = None,
                         min_events: int = 1) -> Path | None:
    """Append a new STATE_<ts>.md to ``_continuity/`` summarizing what
    happened in this session.

    Returns the written path, or None if there's nothing worth recording
    (no audit entries since session_start).

    Designed for atexit — must be cheap and not raise.
    """
    try:
        cont_dir = root / "_continuity"
        cont_dir.mkdir(parents=True, exist_ok=True)

        # Determine session start: most-recent STATE_*.md mtime + small slack
        # OR, if there isn't one, fall back to the boot-time the caller
        # passed via session_id (interpreted as ISO timestamp).
        session_start_iso = None
        if session_id:
            session_start_iso = session_id

        existing = sorted(cont_dir.glob("STATE_*.md"))
        if existing and not session_start_iso:
            # Use latest STATE's mtime as cutoff
            session_start_iso = datetime.fromtimestamp(
                existing[-1].stat().st_mtime,
                tz=timezone.utc).isoformat(timespec="seconds")

        # Pull recent activity from DB
        with db.conn() as c:
            audit_q = "SELECT * FROM audit_log"
            params: tuple = ()
            if session_start_iso:
                audit_q += " WHERE ts >= ?"
                params = (session_start_iso,)
            audit_q += " ORDER BY ts DESC LIMIT 50"
            audit_entries = list(c.execute(audit_q, params))

            if len(audit_entries) < min_events:
                return None  # nothing worth saving

            verdict_counts = {}
            for r in c.execute(
                "SELECT status, COUNT(*) AS n FROM verification_status "
                "GROUP BY status"):
                verdict_counts[r["status"]] = int(r["n"])

            feedback_q = (
                "SELECT user_action, COUNT(*) AS n FROM learning_feedback "
                + ("WHERE ts >= ? " if session_start_iso else "")
                + "GROUP BY user_action"
            )
            feedback_counts = {}
            for r in c.execute(feedback_q, params if session_start_iso else ()):
                feedback_counts[r["user_action"] or "unknown"] = int(r["n"])

            llm_q = (
                "SELECT COUNT(*) AS n, COALESCE(SUM(cost_usd), 0) AS cost "
                "FROM llm_calls "
                + ("WHERE ts >= ?" if session_start_iso else "")
            )
            llm = c.execute(llm_q, params if session_start_iso else ()).fetchone()
            llm_calls = int(llm["n"]) if llm else 0
            llm_cost = float(llm["cost"]) if llm else 0.0

            project_row = c.execute(
                """SELECT p.name, p.code, c.name AS company_name, c.code AS company_code
                   FROM projects p JOIN companies c ON c.company_id = p.company_id
                   WHERE p.is_active = 1 LIMIT 1"""
            ).fetchone()

            latest_snap = c.execute(
                "SELECT id, ts FROM snapshots ORDER BY ts DESC LIMIT 1"
            ).fetchone()

        now = datetime.now(timezone.utc)
        ts_label = now.strftime("%Y%m%d_%H%M%S")
        out_path = cont_dir / f"STATE_{ts_label}.md"

        # Group audit entries by action for the summary
        action_counts: dict[str, int] = {}
        for e in audit_entries:
            action_counts[e["action"]] = action_counts.get(e["action"], 0) + 1

        lines: list[str] = []
        lines.append(f"# Continuity State — {now.strftime('%Y-%m-%d %H:%M UTC')}")
        lines.append("")
        lines.append("> Auto-generated by GUI shutdown hook (Ops-1, 2026-05-10).")
        lines.append("> Summarizes activity since the previous STATE file.")
        lines.append("")
        lines.append("## Session summary")
        lines.append("")
        if project_row:
            lines.append(f"- **Project**: {project_row['name']} ({project_row['code'] or '—'}) "
                         f"under {project_row['company_name']}")
        lines.append(f"- **Audit events this session**: {len(audit_entries)}")
        if action_counts:
            tops = sorted(action_counts.items(), key=lambda x: -x[1])[:8]
            lines.append("  - " + ", ".join(f"{k}: {v}" for k, v in tops))
        lines.append(f"- **Claude calls**: {llm_calls}"
                     + (f" (${llm_cost:.4f})" if llm_cost > 0 else " (Max — no metered cost)"))
        if feedback_counts:
            fb_summary = ", ".join(f"{k}: {v}" for k, v in feedback_counts.items())
            lines.append(f"- **Feedback recorded**: {fb_summary}")
        lines.append("")

        if verdict_counts:
            lines.append("## Verdicts (cumulative across project)")
            lines.append("")
            for k, v in sorted(verdict_counts.items()):
                lines.append(f"- {k}: {v}")
            lines.append("")

        if latest_snap:
            lines.append("## Latest snapshot")
            lines.append("")
            lines.append(f"- `{latest_snap['id']}` (at {latest_snap['ts']})")
            lines.append("")

        lines.append("## Recent audit entries (last 20)")
        lines.append("")
        for e in audit_entries[:20]:
            ts = (e["ts"] or "")[:19]
            target = f"{e['target_type']} {e['target_id']}".strip()
            before = (e["before"] or "")[:30]
            after = (e["after"] or "")[:30]
            ba = f" · `{before}` → `{after}`" if (before or after) else ""
            lines.append(f"- `{ts}` **{e['action']}** — {target}{ba}")
        lines.append("")

        lines.append("## Next session hint")
        lines.append("")
        lines.append("- Read `docs/MANUAL.md` for usage refresher.")
        lines.append("- Check tree's '🔴 ต้องดู' filter for rows still pending.")
        lines.append("- `_versions/snapshots/` has the most recent restore points.")
        lines.append("")

        out_path.write_text("\n".join(lines), encoding="utf-8")
        return out_path
    except Exception as e:
        # Atexit hooks must NEVER raise — just log to stderr
        sys.stderr.write(f"[continuity] write_session_state failed: {e}\n")
        return None


def install_atexit_hook(*, root: Path) -> None:
    """Register an atexit hook that writes STATE on Python shutdown.

    Idempotent — only registers once per process.
    """
    if os.environ.get("COMPLY_NO_ATEXIT_STATE"):
        return  # opt-out for tests / CI
    if getattr(install_atexit_hook, "_installed", False):
        return
    import atexit
    atexit.register(write_session_state, root=root)
    install_atexit_hook._installed = True  # type: ignore
